# Generated by Django 2.0.3 on 2018-03-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('start_date', models.DateField(db_index=True, help_text='Date when employees will start their tour')),
                ('end_date', models.DateField(db_index=True, help_text='Date when employees will end their tour')),
                ('ticket_cost', models.PositiveIntegerField(default=0)),
                ('home_cab_cost', models.PositiveIntegerField(default=0)),
                ('dest_cab_cost', models.PositiveIntegerField(default=0)),
                ('hotel_cost', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('approved', 'approved'), ('rejected', 'rejected'), ('request_for_information', 'request_for_information'), ('submitted_to_finance', 'submitted_to_finance')], db_index=True, default='draft', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approved_by_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by_tour', to='employee.Employee')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_tour', to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of Transport', max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour', to='tour.Transport'),
        ),
    ]
