# Generated by Django 2.0.3 on 2018-03-28 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_type', models.CharField(choices=[('home', 'home'), ('destination', 'destination')], db_index=True, max_length=32)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('sgd', 'sgd'), ('php', 'php')], db_index=True, default='php', max_length=32, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of Hotel', max_length=64, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='tour.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='tour.Currency')),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='approved_by_user',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='dest_cab_cost',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='home_cab_cost',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='hotel_cost',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='ticket_cost',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='transport',
        ),
        migrations.AddField(
            model_name='tour',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(choices=[('plane', 'plane'), ('ship', 'ship'), ('bus', 'bus')], db_index=True, default='plane', max_length=32),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(db_index=True, help_text='Type of Transport', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='tour.Transport'),
        ),
        migrations.AddField(
            model_name='cab',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cab', to='tour.Currency'),
        ),
        migrations.AddField(
            model_name='tour',
            name='dest_cab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_home_dest', to='tour.Cab'),
        ),
        migrations.AddField(
            model_name='tour',
            name='home_cab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_home_cab', to='tour.Cab'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='tour.Hotel'),
        ),
        migrations.AddField(
            model_name='tour',
            name='ticket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='tour.Ticket'),
        ),
    ]
