# Generated by Django 2.0.3 on 2018-03-30 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180328_1010'),
        ('tour', '0002_auto_20180328_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='employee',
        ),
        migrations.AddField(
            model_name='tour',
            name='finance_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_finance_manager', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='tour',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_manager', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='tour',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_worker', to='employee.Employee'),
        ),
    ]
