# Generated by Django 2.0.3 on 2018-03-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20180330_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='dest_cab',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tour',
            name='home_cab',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
