# Generated by Django 2.0.3 on 2018-03-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20180330_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_cost', to='tour.Currency')),
            ],
        ),
        migrations.RemoveField(
            model_name='cab',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Cab',
        ),
        migrations.AddField(
            model_name='hotelcost',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_cost', to='tour.Hotel'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='tour.HotelCost'),
        ),
    ]
