# Generated by Django 2.0.3 on 2018-03-30 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20180330_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='finance_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_finance_manager', to='employee.Employee'),
        ),
    ]
